version: '3'
services:
  ubuntu-ssh:
    build:
      context: .
    image: ubuntu-ssh
    cap_add:
      - SYS_TIME
    ports:
      - "2222:22"
      - "123:123/udp"
    command: /usr/local/bin/set_fake_time.sh tail -f /dev/null
    environment:
      - ROOT_PASSWORD=rootpassword
      - TZ=Europe/Moscow
      - FAKETIME="2022-12-02 00:00:00"
    stdin_open: true
    tty: true
